boxine/bx_py_utils

bx_py_utils/__init__.py
bx_py_utils/models/manipulate.py
bx_py_utils_tests/tests/test_model_manipulate.py
pyproject.toml

It should be not possible to create or update model instance with non-valid data.
So we just call `instance.full_clean(validate_unique=False)` before save call.

Update create_or_update(): validate before save

---

pyproject.toml

Also changes the version string to double quotes. Otherwise make publish will fail because poetry overwrites the line with double quotes and then complains that git reports a diff.

add Florian Braun as an author

---

README.md
bx_py_utils/__init__.py
bx_py_utils/humanize/time.py
bx_py_utils/models/timetracking.py
bx_py_utils/templatetags/humanize_time.py
bx_py_utils_tests/test_app/admin.py
bx_py_utils_tests/tests/test_humanize_time.py
bx_py_utils_tests/tests/test_templatetags_humanize_time.py
pyproject.toml

Will be used in e.g.: django-huey-monitor ;)
The absolute timestamp is available via mouse over tooltip, e.g.:

Add humanize time stuff

---

bx_py_utils/filename.py

Before this changes, a file path will be cleaned, too, e.g.:
```
>>> clean_filename('foo/bar.py')
foobar.py
```

Accept only file names in filename2human_name() and clean_filename()

---

bx_py_utils/test_utils/html_assertion.py

When the type of parts is wrong (most often because forgetting the final `,` in a tuple and thus passing a string), crash immediately.

assert_html_parts: Crash noisily

---

README.md
bx_py_utils/test_utils/assert_queries.py
bx_py_utils_tests/tests/test_assert_queries.py

Assert executed database queries.
Example usage:
```
with AssertQueries() as queries:
func_that_makes_queries()
queries.assert_queries(
query_count=3,
table_names=['foo','bar'],
double_tables=True,
duplicated=True,
similar=True,
)
```

NEW: bx_py_utils.test_utils.assert_queries.AssertQueries()

---

bx_py_utils/filename.py

This function deals with user-defined input, and can be something like `foo / bar`.
Rather than crashing, the function should actually clean the filename.
(Internal link: https://sentry.boxine.de/boxine/octonie/issues/40390/ )

clean_filename: Accept any input

---

bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py

Sometimes, we want to compare a huge text string. `assert_snapshot` would require us to json-encode this.
Add a new variant `assert_text_snapshot` for this use case.

+ assert_text_snapshot

---

bx_py_utils_tests/tests/test_approve_workflow.py

These tests test that the `<title>` is laid out a certain way, but there is no guarantee by Django about that, and we see different strings in practice.
Simply remove them; these lines are not relevant to the functioning of the model.

Remove flaky tests

---

bx_py_utils/graphql_introspection.py
bx_py_utils_tests/tests/graphql_introspection/shopify_product_only_depth2.snapshot.txt
bx_py_utils_tests/tests/test_graphql_introspection.py

When evaluating a query, it can be very helpful to see only a given depth (like 2 or 3) to get a good overview of the available fields, but not recurse any deeper. Add that as an option.

graphql_introspection: Add max_depth argument

---

bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py

Usually, snapshot files are created as `test_name.snapshot.txt`. For XML files it may be beneficial to name them `.xml`, so allow passing in an extension.

assert_text_snapshot: Allow specifying the extension

---

README.md
bx_py_utils/test_utils/assertion.py
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_assertion.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py

* Add `assert_text_equal` and use it for `assert_text_snapshot`
* Use existing `assert_equal` for `assert_snapshot`
So the snapshot tests will raise a error with a ndiff. This may be helpful in CI pipelines.

Enhance snapshot test helper: Display ndiff error messages

---

Makefile

Add a test target as an alias for pytest, so that the standard `make test` does the right thing.

+ make test

---

bx_py_utils_tests/tests/test_test_utils_snapshot.py

Remove a `print` that snuck through.

Remove debug code

---

bx_py_utils/compat.py

Restore 3.6/3.7 compatibility.

compat: Remove positional-only marker in arguments

---

README.md
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py

The current snapshot tests used JSON and JSON can't serialize all types of Python objects. e.g.:
UUID, datetime, Decimal etc. It's possible to expand the JSONEncoder to serialize them. But then a
compare beween a UUID instance or a string that looks like a UUID is not possible ;)

Add assert_py_snapshot() that use PrettyPrinter() to support more Python objects

---

pyproject.toml

This one was overlooked: It's only needed in
https://github.com/boxine/bx_django_utils/tree/master/bx_django_utils/data_types/gtin

Remove obsolete "python-stdnum"

---

README.md
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py

If a snapshot function will be used indirect by a helper in a other project file, then we have to
pass the correct file path to get the correct caller stack frame.

Add optional "self file path" to all snapshot functions

---

README.md
bx_py_utils/auto_doc.py
bx_py_utils_tests/tests/test_readme.py

Use `inspect.getsourcelines()` instead of undocumented `inspect.findsource()`:
https://docs.python.org/3/library/inspect.html#inspect.getsourcelines
Change the pattern with `start` + `end` and deprecated the old `lnum`

Add start+end line number to auto doc links

---

README.md
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py

Explicitly and manually convert text.

assert_text_snapshot: Make sure it fails if newlines change

---

README.md
bx_py_utils/html_utils.py
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_html_utils.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot_assert_html_snapshot_1.snapshot.html
pyproject.toml

Fix https://github.com/boxine/bx_py_utils/issues/94
`etree.tostring()` with `pretty_print` can't handle whitespaces very good. It also changes the HTML
document more than BeautifulSoup.
Split the code and create intepend useable functions:
* `validate_html()`
* `pretty_format_html()`
`assert_html_snapshot()` will use both as default.
`validate_html()` may be enhanced. There are a few more ways to validate HTML documents, but the
intention here is just to raise an error on really broken documents. Because `BeautifulSoup` will
consume broken documents: Validate them before pretty format.

Refactor assert_html_snapshot() and use BeautifulSoup

---

README.md
bx_py_utils/test_utils/mocks3.py
bx_py_utils_tests/tests/test_test_utils_mocks3.py

boto3 closes file objects, see:
https://github.com/boto/s3transfer/issues/80
Add this to our mock for `upload_fileobj()`, too.

S3 mock closed files, too.

---

bx_py_utils/auto_doc.py
bx_py_utils/test_utils/mocks3.py

In practice, when there are large files in the mocks3, printing the `repr` can take quite some time, on the order of 10s!
Instead, only extract the bytes we care, and calculate the repr of those, and then cut that off if necessary, which makes the whole task finish in <100ms.

debug_long_repr: Cut off long bytes

---

README.md
bx_py_utils/html_utils.py
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot_assert_html_snapshot_by_css_selector_1.snapshot.html

With this PR, you'll be able to perform HTML snapshot tests on specific HTML elements only (vs snapshot testing the whole HTML page).
Simply specify the query selector using:
assert_html_snapshot(got=html, query_selector='div.test-me')

add query_selector param to assert_html_snapshot to limit snapshots to one or more specific html elements

---

README.md
bx_py_utils/test_utils/mocks3.py
bx_py_utils_tests/tests/test_test_utils_mocks3.py

Support `Callback` and support passing all origin arguments.

Enhance bx_py_utils.test_utils.mocks3.PseudoS3Client.download_fileobj()

---

README.md
bx_py_utils/html_utils.py
bx_py_utils_tests/tests/test_html_utils.py

We passed `formatter=None` to beautiful_soup.prettify in an effort to not mess with the input.
But this _MASSIVELY_ messes with the input and does not correctly escape it.
This could even lead to Cross-Site-Scripting (XSS) vulnerabilities! Fortunately this function is not used on user input, but still.
Add a test to ensure correct encoding.

Fix XSS vulnerability in assert_html_snapshot

---

README.md
bx_py_utils/auto_doc.py
bx_py_utils_tests/tests/test_readme.py
poetry.lock
pyproject.toml

We test only with Python 3.8-3.10 and min. Python is 3.7. So we didn't need the extra limitation.
Bugfix test by remove pytest "--import-mode=importlib" option.

Remove pdoc "python>=3.7"

---

README.md
bx_py_utils/rison.py
bx_py_utils_tests/tests/test_rison.py

RISON is used by the OpenSearch dashboard.
There is a public PyPi package for RISON, but it's unmaintained and not installable with a recent pipenv.
The language is sufficiently simple that we can just implement it.

Add RISON support

---

bx_py_utils/rison.py
bx_py_utils_tests/tests/test_rison.py

Incredibly, `now-7d` does NOT to be quoted in RISON. Add this to make nicer URLs.

RISON: less quoting

---

.github/workflows/pythonapp.yml
Makefile
bx_py_utils/__init__.py
poetry.lock
pyproject.toml

Use https://github.com/jedie/manageprojects and the CookieCutter Template: https://github.com/jedie/cookiecutter_templates/tree/main/poetry-python to modernize the project setup.
But use only a few ideas from the origin template:
* set min. Python version to v3.9
* Add `mypy` (But don't include it in tests/CI)
* Bugfix poetry bootstrap by call `python3 -m venv .venv` first, see: https://github.com/python-poetry/poetry/issues/6371
* Use the official way to install poetry, see: https://python-poetry.org/docs/#installing-with-the-official-installer (Personally i prefere using pipx)
* Remove hardcoded version number from `bx_py_utils/__init__.py`, so we must only change the version in `pyproject.toml`

Modernize project setup

---

.github/workflows/pythonapp.yml
Makefile
README.md
bx_py_utils/__init__.py
bx_py_utils/auto_doc.py
bx_py_utils_tests/tests/test_auto_doc.py
bx_py_utils_tests/tests/test_readme.py
poetry.lock
pyproject.toml

The function to replace/assert text blocks in text files are usefull for other other situation, too.
e.g.:
https://github.com/jedie/cookiecutter_templates/commit/9df0809de97c2cf8aeffd3dc9419373b1b59ffcf#diff-6f7187cf14e9aedb99b9b0ec2c64898af27dffdb35744475581a22b64b89afa8R24-R50
;)
Just extract the function and test them separately.

Seperate assert_readme_block() from assert_readme()

---

README.md
bx_py_utils/auto_doc.py
pyproject.toml

`bx_py_utils.auto_doc.assert_readme_block()` is a nice helper that can be used independ of `pdoc`.
e.g.: https://github.com/jedie/manageprojects/pull/43

Fix #157 and make "pdoc" optional

---

README.md
bx_py_utils/test_utils/unittest_utils.py
bx_py_utils_tests/tests/test_doctests.py

The "normal" way to add doctests to unittests is described here:
https://docs.python.org/3/library/doctest.html#unittest-api
But it's needed to change the unittest setup and how tests loaded. With the `BaseDocTests` it's just needed to ass another `TestCase` and you are done ;)
This will increase the number of tests from 88 to 167, because we have already many doctests and after replace pytests with unittests they was not tested. But hey, no changes needed, all doctests are still correct ;)

NEW: Helper to add doctests into unittest by just adding a TestCase

---

poetry.lock
pyproject.toml

Install flynt/isort/Pygments via darker "extras", to get always compatibility version combinations. 
See: https://github.com/akaihola/darker/issues/472

Fix darker/flynt/isort/Pygments combination

---

Makefile
README.md
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py
pyproject.toml

Sometimes it's helpfull to add a "suffix" to a snapshot name without to specify the full name. e.g.: Split a html snapshot by current Django version.
Add optional `name_suffix` to all existing snapshot functions.
Additional changes: Speedup tox by run it parallelized as default.

Add a name "suffix" to all snapshot functions

---

README.md
bx_py_utils/auto_doc.py
bx_py_utils/filename_matcher.py
bx_py_utils/test_utils/unittest_utils.py
pyproject.toml

Refactor FnmatchExclude and use a flat function for the matching: For the "auto_doc" is still a callable usefull, but for doc test we can just use a normal function.
Enhance also the `subTest` names in DocTest to the real function package dot-name.

Enhance BaseDocTests and add optional argument to exclude file paths

---

README.md
bx_py_utils/test_utils/unittest_utils.py
bx_py_utils_tests/tests/doctest_skip.py
bx_py_utils_tests/tests/test_auto_doc.py
bx_py_utils_tests/tests/test_doctests.py
pyproject.toml

The `filename_matcher()` was used the wrong way around.
Enhance also the implementation and use `DocTest.filename` for exclusion. So it's the complete path including the file name, too.
Bugfix also typo: `AudoDocTestCase` -> `AutoDocTestCase`, too.

Bugfix run_doctests and `excludes`

---

README.md
bx_py_utils/test_utils/assertion.py
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py

state the snapshot name or file when a snapshot's content changes. this makes it easier to identify which snapshot was affected, especially with snapshots without explicit name.
also simplify the underlying assert functions by defining their fallback message in the argument definition.
this is what it looks like after the changes.
```
<traceback>
bx_py_utils.test_utils.snapshot.SnapshotChanged: /home/flbraun/Documents/myproject/test/test_classname_methodname_2.snapshot.json
--- got
+++ expected
<the diff>
```

state the snapshot name or file when a snapshot's content changes

---

README.md
bx_py_utils/test_utils/requests_mock_assertion.py
bx_py_utils_tests/tests/test_requests_mock_assertion.py
pyproject.toml

Don't try to deserialize when the request body is None.
Fix errors like:
```
Traceback (most recent call last):
File "bx_py_utils/bx_py_utils_tests/tests/test_requests_mock_assertion.py", line 129, in
test_assert_json_requests_mock_with_none
assert_json_requests_mock(mock=m, data=[{'request': 'GET http://test.tld/'}])
File "bx_py_utils/bx_py_utils/test_utils/requests_mock_assertion.py", line 44, in
assert_json_requests_mock
history = build_requests_mock_history(mock, only_json=True)
File "bx_py_utils/bx_py_utils/test_utils/requests_mock_assertion.py", line 16, in
build_requests_mock_history
json_data = request.json()
File "bx_py_utils/.venv/lib/python3.10/site-packages/requests_mock/request.py", line 155, in json
return json.loads(self.text, **kwargs)
File …
```

Bugfix requests_mock_assertion if body is empty

---

README.md
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py

To make the function usable in another way: Rename `_get_snapshot_file()` and make the hardcoded `.snapshot` changeable.

Make get_snapshot_file() public and more flexible

---

bx_py_utils/rison.py
bx_py_utils_tests/tests/test_rison.py

Allow dots, and sort keys, as demanded by the spec.

Follow RISON spec more closely

---

bx_py_utils/doc_write/README.md
bx_py_utils/test_utils/log_utils.py
bx_py_utils_tests/tests/test_test_utils_log_utils.py

NoLogs installed no handlers. But what happens if you don't install any handlers is that Python's logging framework automatically logs into a last-resort handler to stderr.
Fix this by installing a `NullHandler`, and add both a test capturing `sys.stderr` as well as just executing it so we can see it (in case the sys.stderr` capture fails).

Fix NoLogs

---

README.md
bx_py_utils/filename_matcher.py
bx_py_utils_tests/tests/test_doctests.py
pyproject.toml

Sadly, the changes:
https://github.com/boxine/bx_py_utils/pull/180/commits/f82cb3b7313015332b44401c24d735a418385328#diff-5ddedf7646e83b7133361b398ae2746ea82dc77a3ba2ef39409fc2b503f04758 are not backward compatible, because `excludes=None` will crash in `filename_matcher()`. Fix this here.

Bugfix run_doctests and optional excludes

---

README.md
bx_py_utils/test_utils/deny_requests.py
bx_py_utils_tests/tests/test_readme.py
bx_py_utils_tests/tests/test_test_utils_deny_requests.py
pyproject.toml

Tests should normaly never made real requests. You have to take extra care that this does not happen. Add helper to make this easy.

NEW: bx_py_utils.test_utils.deny_requests

---

bx_py_utils/doc_write/README.md
bx_py_utils/doc_write/api.py
bx_py_utils/doc_write/cfg.py
bx_py_utils_tests/tests/test_doc_write_api.py
pyproject.toml

If DocWrite strings will be remove in code base, so that a *.md file is completely obsolete, then this file will no be updated and not be removed, because it's just not "seen" and touched.
Add a `delete_obsolete_files` to config to remove all "unseen" *.md files from base path to cleanup.

Expand DocWrite with optional `delete_obsolete_files`

---

README.md
bx_py_utils/auto_doc.py
bx_py_utils/dict_utils.py
bx_py_utils/file_utils.py
bx_py_utils/pyproject_toml.py
bx_py_utils/string_utils.py
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/__init__.py
bx_py_utils_tests/tests/test_test_utils_snapshot.py
poetry.lock
pyproject.toml

Activate typeguard by `install_import_hook()` in `bx_py_utils_tests/tests/__init__.py` so it's
activated for unittests, only.
Fix some wrong typehints. Mainly missing ` | None` in optional keyword arguments.

Check type annotations in tests via typeguard

---

bx_py_utils/doc_write/README.md
bx_py_utils/doc_write/api.py
bx_py_utils_tests/tests/test_doc_write.py
bx_py_utils_tests/tests/test_doc_write_api.py

It should be never missed to commit docwrite changes. So return more information about the generation and use it in tests.

Fail tests if docs are not up2date

---

README.md
bx_py_utils/test_utils/mocks3.py
bx_py_utils_tests/tests/test_test_utils_mocks3.py

Mock `copy_object` as described on https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/copy_object.html .

PseudoS3Client: Implement copy_object

---

README.md
bx_py_utils/doc_write/README.md
bx_py_utils/doc_write/api.py
bx_py_utils/doc_write/cfg.py
bx_py_utils/doc_write/data_structures.py
bx_py_utils/doc_write/docstrings.py
bx_py_utils/doc_write/macro.py
bx_py_utils/import_utils.py
bx_py_utils_tests/doc_write_macros.py
bx_py_utils_tests/tests/test_doc_write_api.py
bx_py_utils_tests/tests/test_doc_write_cfg.py

Sometimes it's helpful to add dynamic content to the documentation. This can be done with macros.
Macros are defined in the DocString block by using the `DocWriteMacro:` prefix
and the callable name as dotting path. e.g.:
DocWriteMacro: foo.bar.baz

NEW: DocWriteMacro: Add callables into DocWrite to complete the docs

---

.github/workflows/tests.yml
README.md
bx_py_utils/environ.py
bx_py_utils/stack_info.py
bx_py_utils/test_utils/assertion.py
bx_py_utils/test_utils/snapshot.py
bx_py_utils_tests/tests/test_environ.py
bx_py_utils_tests/tests/test_utils/test_mocks3.py
pyproject.toml

Also run `pyupgrade --py310-plus` against the codebase as that is our minimum supported version.

Compatibility with Python 3.13

---

bx_py_utils_tests/publish.py

in 50f34991 pipenv was removed from the project in favor of uv, but `pipenv check` is still used in the publishing script. it effectively does nothing because there is no Pipfile containing dependencies that could be checked.
unfortunately uv doesn't have equivalent functionality (yet), but there are other ways to ensure safe/up-to-date dependencies (e.g. using dependabot).

remove remainders of pipenv

---

pyproject.toml
uv.lock

Current call of "make publish" ran into: "No module named build"
Just add the needed "build" package. Think it was missed on pip-tools -> uv migration. Maybe we can also build via uv in the future.
Also remove the pip-tools work-a-round for https://github.com/jazzband/pip-tools/issues/1866 It's obsolete with uv.

Bugfix "make publish"

---

README.md
bx_py_utils/test_utils/mocks3.py
bx_py_utils_tests/tests/test_utils/test_mocks3.py

Forbid commonly used invalid keys (starting with slash or too long).

PseudoS3Client: Check keys

---

README.md
bx_py_utils/dict_utils.py
bx_py_utils_tests/tests/test_hash_utils.py

Sometimes doing it right is hard.
Using `is` doesn't work if we have two string with the same values but different `id()`. Python aggressively reuses immutable objects like strings to optimize memory usage.
Nevertheless, I have seen in practice that this is exactly what happens: Same value but different objects.
It's hard to test this. All of this doesn't create different objects, e.g.:
```
value1 = 'foobar'
value2 = 'foo' + 'bar'
value2 = str(value1)
value2 = value1[:]
value2 = copy.deepcopy(value1)
value2 = "".join([value1])
```
What works for me is: `bytearray(value1, 'utf-8').decode('utf-8')` ... Using this in our tests.

Bugfix compare functions edge cases

---

bx_py_utils_tests/publish.py

We replaced this make target with "make lint" in https://github.com/boxine/bx_py_utils/pull/234/
Anyway: Remove it from "publish", because run the tests will check the code style with: `ProjectSetupTestCase.test_code_style()`

Bugfix publish: Remove "make fix-code-style"
