boxine/bx_py_utils

bx_py_utils_tests/test_project/publish.py, pyproject.toml
Use https://github.com/jedie/poetry-publish for easier publish a new release on PyPi.
Add add more meta information to pyproject.toml
=> Make "make publish" alive

bx_py_utils/models/manipulate.py, bx_py_utils_tests/test_app/models.py, bx_py_utils_tests/tests/test_model_manipulate.py, bx_py_utils_tests/tests/utils.py
Add:
* bx_py_utils.models.manipulate.create_or_update()
* bx_py_utils_tests.tests.utils.MockDatetimeGenerator()
* bx_py_utils_tests.tests.utils.parse_dt()
=> Add model helper: create_or_update() and some test tools

bx_py_utils/dict_utils.py
This helper function can be used to extract items from a dict by key.
=> dict_utils: Add pluck helper function

bx_py_utils/__init__.py, bx_py_utils/models/manipulate.py, bx_py_utils_tests/tests/test_model_manipulate.py, pyproject.toml
=> Add "call_full_clean" to "create_or_update()" to skip "full_clean()" call

bx_py_utils/stacktrace.py, bx_py_utils_tests/tests/test_stacktrace.py
adds helper methods for producing clean stacktraces. prerequisite for an upcoming PR.
=> add the new stacktrace module

bx_py_utils/dbperf/cursor.py, bx_py_utils/dbperf/query_recorder.py, bx_py_utils_tests/tests/test_dbperf.py
This PR implements the SQLQueryRecorder context manager and all necessary utilities it builds on.
=> add the new dbperf module

README.md, bx_py_utils/view_utils/dynamic_menu_urls.py, bx_py_utils_tests/test_app/templates/dynamic_view_menu/demo.html, bx_py_utils_tests/test_app/templates/dynamic_view_menu/index.html, bx_py_utils_tests/test_app/urls.py, bx_py_utils_tests/test_app/views/dynamic_view_menu.py, bx_py_utils_tests/test_project/urls.py, bx_py_utils_tests/tests/test_dynamic_view_menu.py, pyproject.toml
Test demo menu looks like this:
=> Add DynamicViewMenu - Register views to build a simple menu

bx_py_utils/test_utils/html_assertion.py
=> Create better error messages in assert_messages()

bx_py_utils/test_utils/html_assertion.py, bx_py_utils_tests/tests/test_html_assertion.py
Using the our new `assert_equal()` reports better error messages than `self.assertCountEqual()` ;)
=> Enhance assert_messages()

README.md, bx_py_utils/test_utils/snapshot.py, bx_py_utils_tests/tests/test_test_utils_snapshot.py
Add a helper function for snapshot tests.
=> Add snapshot test functionalities

README.md, bx_py_utils/path.py, bx_py_utils/stack_info.py, bx_py_utils/test_utils/filesystem_utils.py, bx_py_utils/test_utils/snapshot.py, bx_py_utils_tests/tests/test_path.py, bx_py_utils_tests/tests/test_stack_info.py, bx_py_utils_tests/tests/test_test_utils_filesystem_utils.py, bx_py_utils_tests/tests/test_test_utils_snapshot.py
Get the path and the name from stack ;)
Add a few needed helpers, too:
* `FileWatcher()`
* `path.assert_is_dir()`
* `path.assert_is_file()`
* `stack_info.last_frame_by_path()`
=> Make snapshot path and name optional #65 

README.md, bx_py_utils/__init__.py, bx_py_utils/anonymize.py, bx_py_utils/auto_doc.py, bx_py_utils/compat.py, bx_py_utils/graphql_introspection.py, bx_py_utils/hash_utils.py, bx_py_utils/humanize/pformat.py, bx_py_utils/iteration.py, bx_py_utils/processify.py, bx_py_utils/test_utils/assertion.py, bx_py_utils/test_utils/datetime.py, bx_py_utils/test_utils/mock_aws_secret_manager.py, bx_py_utils/test_utils/mock_boto3session.py, bx_py_utils/test_utils/snapshot.py, bx_py_utils/test_utils/time.py, bx_py_utils_tests/tests/test_readme.py, pyproject.toml
Use "pdoc" for the real job of collecting information.
Generate a list similar to our existing one.
Update the README by tests, similar to our snapshot test helper ;)
Update some DocStrings.
Example result: https://github.com/boxine/bx_py_utils/blob/auto-doc/README.md
Think a later PR may add deeplinks to github source. Sadly pdoc doesn't collect the line number. So
we can't add a anchor link :(
=> Audo generate "Existing stuff" README.md

bx_py_utils/test_utils/snapshot.py, bx_py_utils_tests/tests/test_test_utils_snapshot.py
`assert_text_snapshot()` has add `.snapshot` double times if "auto names" are used, because
`_get_caller_names()` adds `.snapshot` already...
Merge code parts into a new `_get_snapshot_file()` helper function and test this function separate.
Add also a default `extension` argument to `assert_snapshot()` and `assert_py_snapshot()`. So all
functions has the same signature.
=> Bugfix assert_text_snapshot()

README.md, bx_py_utils/test_utils/requests_mock_assertion.py, bx_py_utils_tests/tests/test_requests_mock_assertion.py, bx_py_utils_tests/tests/test_requests_mock_assertion_assert_json_requests_mock_snapshot_1.snapshot.json, bx_py_utils_tests/tests/test_requests_mock_assertion_assert_requests_mock_snapshot_1.snapshot.json
Add assert function to check non JSON requests and add snapshot variants, too.
=> Enhance "assert requests mock"

README.md, bx_py_utils/file_utils.py, bx_py_utils_tests/tests/test_file_utils.py
add:
* `NamedTemporaryFile2()`
* `get_and_assert_file_size()`
=> Add file utils

Makefile
See: https://github.com/ikamensh/flynt/issues/42
=> Bugfix flynt call

README.md, bx_py_utils/test_utils/mocks3.py, bx_py_utils_tests/tests/test_test_utils_mocks3.py
Also make sure to use botocore's exceptions if available, because client applications might catch those.
=> PseudoS3Client: Implement head_object

bx_py_utils/auto_doc.py
The method has changed, use the updated one.
=> update to new pdoc version

.github/workflows/pythonapp.yml, Makefile, README.md
It's already on my machine. Drop 3.6, which we aren't using anywhere anymore afaik.
=> Add Python 3.10 to test matrix

README.md, bx_py_utils/test_utils/snapshot.py, bx_py_utils_tests/tests/test_test_utils_snapshot.py
Allow taking snapshots of binary files, e.g. Excel.
=> + assert_binary_snapshots

README.md, bx_py_utils/file_utils.py, bx_py_utils_tests/tests/test_file_utils.py
Add a function to create a filename from untrusted inputs.
=> + safe_filename helper function

README.md, bx_py_utils/file_utils.py, bx_py_utils_tests/tests/test_file_utils.py
Short the file name (and keep the last suffix).
based on https://github.com/boxine/bx_py_utils/pull/143
=> NEW: `cut_filename()`

README.md, bx_py_utils/test_utils/mocks3.py, bx_py_utils_tests/tests/test_test_utils_mocks3.py
Implement more arguments to download_file.
=> mocks3: Add more arguments to download_file

.editorconfig, .flake8, pyproject.toml
Apply some updates via https://github.com/jedie/manageprojects
The interesting one: The `tox` setup just calls `make install`, so we must not specify the `deps`
=> Project updates

bx_py_utils_tests/publish.py
Use standard library Python rather than `cli_base` (I can't even find the package).
=> fix publish command

bx_py_utils/doc_write/README.md, bx_py_utils/doc_write/docstrings.py, bx_py_utils_tests/publish.py, bx_py_utils_tests/tests/test_doc_write_api.py, pyproject.toml
- fix publish command
- Consistent order in auto-generated documentation
=> consistent doc order
